### ISSUE TITLE
link to the official implementation: https://github.com/ysymyth/tree-of-thought-llm

### ISSUE THREAD

**Issue by ysymyth** [kyegomez/tree-of-thoughts#54]
hi @kyegomez thanks for implementing our work!

as pointed out in https://github.com/ysymyth/tree-of-thought-llm/issues/17, would you mind linking to our official repo in your README.md to avoid any confusion? thanks in advance!

**Comment by kyegomez** [comment]
This isn't an issue with the code, but rather your own ego. Please reframe from applying issues non related to the code, we're not here to play politics we're here to improve algorithms, our implementation is radically different from yours almost to the point where it is completely different.

**Comment by kyegomez** [comment]
Reputation is meaningless when compared against function and usability,

and no this is OUR implementation of Tree of Thoughts, and this is not very misleading I never said this was THE DEFINITIVE IMPLEMENTATION OF tree of thoughts.

Stop wasting your time and contribute some code that helps if not do not seek conflicts

**Comment by Ber666** [comment]
The response is self-contraditing😅. If you want to claim your repo is "radically different from" the Tree of Thoughts paper, you should not use the title and even the figure from the paper as clickbait.

**Comment by kyegomez** [comment]
How?

This happens all the time, this is open source. Everything is open source and free reputation and originality do not exist here.

For example, Lucid does not do this because he is implementing papers under his own name. I am as well. This is Kye Gomez tree of thoughts
https://github.com/lucidrains

**Comment by CyrusOfEden** [comment]
@kyegomez imagine how @lucidrains would respond in this situation.

**Comment by kyegomez** [comment]
Probably alot nicer @CyrusOfEden if someone did not outright command them to reference their repo. If they had not commanded me we would not be here arguing and wasting time instead of improving the algorithm

**Comment by CyrusOfEden** [comment]
@kyegomez I see you did everything lucidrains would do to attribute, but I imagine if he were here that he'd work with @ysymyth to find a common ground. 

The winds of the world blow, and it is up to you to adjust your sail. There is a way things flow, and when we don't mind the flow we can find ourselves at odds with the world. 

As a builder I appreciate your code more than the original repo. I was even excited to collaborate with you, but now I'm not so sure based on your behaviour. 

I believe the better move for the long term game would be to update the README to say something akin to "inspired by Shunyu et al's work on Tree of Thoughts (original implementation here)". Keep the repo name, and hats off to you, you have the PyPI package as well. 

It would be an honourable thing to do mate, you're tarnishing your own reputation right now with your wringing. Take what you have. Play the long game.

**Comment by CyrusOfEden** [comment]
@danny-avila 

@ysymyth's repo provides 3 specific implementations of tree of thoughts for 3 different games. After 25m it was unclear to me how I would use it in my own projects. It is the code for one of the first of a handful of recent papers that are discovering that guiding the generation of the next token through as a sort of graph search through the possible completions. 

Like if you wanted to get an LLM to solve Sudoku, instead of rolling the dice with a zero shot and hoping it'll work, or even adding "let's think step by step", you use the LLM to generate the next number repeatedly, backtracking if the partial solution is incorrect.

The papers are finding that graph search algorithms like Breadth First Search, Depth First Search, and others are a useful "layer of reasoning" to apply on top of LLM generation. 

@kyegomez's repo implements BFS and DFS tree of thoughts in a manner where you can upgrade your generative LLM apps to use it. It was quickly apparent to me how I would use it in my projects.

**Comment by ddxgz** [comment]
It's a lot easier to simply add a link to the paper's github repo, instead of arguing.

**Comment by Collin-Budrick** [comment]
How hard is it to mention the original inspiration for your repository? Even if it's modified (which is what a fork of any project is). You look better to the community when you're transparent about crediting your work.

I really can't believe this had to be stated.

Your work had the potential to create a collaborative community with the original authors and other developers; but that bridge fell and now other developers who stumble across this will have second thoughts about collaborating with you.

Just seems like a disappointment it turned out this way. There's time to make things right by reaching out the him and setting things straight, but I have a feeling that's wishful thinking.

**Comment by lucidrains** [comment]
ah hey all, just noticed i was tagged on this

@kyegomez i think what you are doing is valuable work. however, you should empathize with the authors here, as it takes a lot of effort to get to the point of contributing even a single paper. the authors are also staking their future careers on each paper they publish. for their idea to be fairly evaluated in the academic framework, reviewers cannot be misled into thinking this is the official repository. therefore, i encourage you to add a single link to the official repository; that is all that you need to do

**Comment by CyrusOfEden** [comment]
![](https://media1.giphy.com/media/15BuyagtKucHm/giphy.gif)

**Comment by kyegomez** [comment]
@lucidrains I have referenced their implementations in the readme.
