### ISSUE TITLE
Comment?

### ISSUE THREAD

**Issue by oaustegard** [kyegomez/tree-of-thoughts#74]
Care to comment on the assertion made in https://github.com/princeton-nlp/tree-of-thought-llm#readme ?

**Comment by kyegomez** [comment]
Hey I implemented my own implementation of the paper, it blew up because people wanted to use it. They're mad they their repo didn't blow up because they didn't release the code for it 2 weeks. They want me to link their repo and are trying to force me even though I took absolutely 0 of their code. Implemented the entire paper based on 4 phrases, dfs, bfs, generate thoughts, evaluate thoughts
