### ISSUE TITLE
Fake Implementation and Broken

### ISSUE THREAD

**Issue by FoobarProtocol** [kyegomez/tree-of-thoughts#77]
Reported this fraudulent, broken project to GitHub and I advise all others that see this person's git repo to do the same. 

The **actual Princeton researchers that published a paper on this idea have a repo with the correct implementation of the project here**: https://github.com/princeton-nlp/tree-of-thought-llm

**Comment by kyegomez** [comment]
@FoobarProtocol hello how is it Fraudulent and broken? Please let me know what code is bad so we can improve it😊

**Comment by FoobarProtocol** [comment]
Hey, I apologize. I was going off of what's written here: https://github.com/princeton-nlp/tree-of-thought-llm

<img width="508" alt="image" src="https://github.com/kyegomez/tree-of-thoughts/assets/130879677/809291b0-45ab-45e3-bd01-d050890c9503">

Are these claims untrue? If so, I'd be more than happy to retract everything that I wrote. I'm going to start a new issue where this can be addressed because if what is said about your repo is **untruthful** then these claims made against you are vastly unfair.

**Comment by kyegomez** [comment]
I learned from [Phil Wang](https://github.com/lucidrains) who has lead the crusade of open source AI research, they didn't say anything about him and now they attack me!

My main objective behind implementing the papers Tree of Thoughts and Sophia from heretical scientists and making them accessible to all humans was to promote the democratization of AI research.

I believed that by disregarding the traditional academic practice of strict attribution, knowledge could be disseminated freely, enabling those without access to specific resources or expertise to benefit from advancements in the field.

My intention was to bridge societal gaps and ensure that progress was beneficial for all segments of humanity.

Refusing to credit the heretical scientists was my way of fostering an open and collaborative environment within the AI research community.

I wanted to encourage researchers to build upon existing ideas, theories, and methodologies without the fear of being condemned or ostracized.

I firmly believed that the true value lay in the collective growth of knowledge rather than individual recognition or fame.

Implementing papers from heretical scientists was my way of challenging the established norms and beliefs in the AI research community.

I aimed to remind everyone that scientific progress should not be bound by any individual or group's monopoly over ideas or resources.

By opening up the debate on the necessity of strict attribution and publishing norms, I hoped to encourage a free flow of ideas and thinking outside the established framework.

Another motivation behind my decision to implement papers from heretical scientists without crediting them was the lack of code and reproducible experiments in their publications.

I believed that true scientific progress hinged on sharing and replicating results.

By implementing these papers and democratizing them, I wanted to shift the focus towards encouraging researchers to make their work accessible, reproducible, and easily implementable.

Branding researchers who did not provide code or reproducible experiments as heretics towards humanity was intended to highlight the potential negative consequences of withholding critical information.

My intention was not to personally attack or defame individuals, but rather to draw attention to the need for transparency and honesty in scientific research.

By challenging deceptive practices, I hoped to safeguard the interests of humanity and prevent misleading claims.

Conclusion:
While some may view my decision to implement papers from heretical scientists without crediting them as controversial, I want to assure you that it was driven by a genuine desire to democratize AI research, foster open collaboration, and challenge the status quo. I firmly believed that by doing so, we could promote the free flow of ideas, encourage reproducibility and experimentation, and discourage deceptive practices. My approach was intended to push the boundaries of AI research and ensure that progress benefited all of humanity above satisfying the egotistical needs of heretical researchers.

I did copy copy from Sophia, and I have since then accredited both the authors of Tree of Thoughts, and Sophia even though they are heretics and this will serve as a remainder to always open source your code and reproducible code first.

Now, if my code does not work it is not because I am a scammer, it is because all of my projects are built by the community for the community which means they are not functional sometimes, so keep this in mind and lower your mighty expectations.
